### ISSUE TITLE
a problem coming out when I use the command ~/fiber$ ./setup_angr_env.sh [dir_name] [venv_name]

### ISSUE THREAD

**Issue by zzhnobug** [fiberx/fiber#3]
when I use the command ~/fiber$ ./setup_angr_env.sh [dir_name] [venv_name], it indicates that the installing claripy requires angr-only-z3-custom. However, when visiting pypi.org/simple/angr-only-z3-custom, it gets a 404 error. I visit pypi.org/simple and cannot find angr-only-z3-custom, but angr-z3 instead. Could you please tell me what I should do to successfully set up? Thank you.

**Comment by hz128** [comment]
Hi,
Thanks for pointing this out! It seems that pypi has removed the old package "angr-only-z3-custom" that is used by the specific version of claripy in fiber. I'm not sure about the reason behind this removal. To fix this I changed the package dependency of claripy in fiber:

https://github.com/fiberx/claripy-fiber/commit/87509180a75325121807689a712dc039e654b9e1

It should work now, you can try to remove and re-install fiber. Let me know if there are still issues. Thanks!

**Comment by zzhnobug** [comment]
It works. Thanks!
