### ISSUE TITLE
Fail to match the patch

### ISSUE THREAD

**Issue by zzhnobug** [fiberx/fiber#4]
Hi, in the 0x2 step, I use the command (venv_name)~/fiber$ python pick_sig.py [patch_list] [reference kernel source] [output_file] [symbol_table,...]. I tried angler_img_20160513/20170513, image_G9300_160909 with their symbol tables separately. But the result turns out to be "Fail to match the patch" for every patch in the example. Could you please help me with it? Thanks.
Here is my complete command:
(fiber_env) hadoop@ubuntu:~/fiber$ python pick_sig.py ~/fiber/examples/patch_list ~/fiber/examples/imgs/angler_img_20170513 ~/fiber/examples/ext_list ~/fiber/examples/imgs/angler_img_20170513.sym

**Comment by hz128** [comment]
Hi,
You need the reference kernel source code instead of the kernel image as the second parameter for pick_sig.py. Please refer to the documents for the repo and commit number of the source code we use for the example. Thanks.
