### ISSUE TITLE
When will the fiber tool support to check the patch involving inline function?

### ISSUE THREAD

**Issue by qiuguoping** [fiberx/fiber#5]

**Comment by hz128** [comment]
Hi, Guoping,

We already have some experimental code to deal with inline functions, but they haven't been merged to the main repository yet. The main issue is that we haven't sufficiently tested the solution and are not sure about its effectiveness, the code may also need further development and improvement. Currently we are running more tests regarding the solution, hopefully we can release the new features soon in months.

**Comment by qiuguoping** [comment]
Thank you for your reply in time, I am looking forward to your good news very much.
